#!/bin/bash
# Quick version info display for Astor AI

VERSION=$(cat VERSION 2>/dev/null || echo "unknown")
CHANGELOG_LINE=$(grep -A 1 "## \[$VERSION\]" CHANGELOG.md 2>/dev/null | tail -1 || echo "No release date found")

echo "╔═══════════════════════════════════════════════╗"
echo "║           🌟 ASTOR AI VERSION INFO           ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "  Version:      $VERSION"
echo "  Release:      Enterprise Launch"
echo "  Date:         December 10, 2025"
echo "  API Version:  v1"
echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║                CORE FEATURES                  ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "  ✓ Life Events Prediction Engine"
echo "  ✓ Advanced Vedic Astrology (Dasha, Panchang)"
echo "  ✓ Yoga Detection System"
echo "  ✓ AI Interpretations (Multi-LLM + RAG)"
echo "  ✓ Compatibility Analysis (Vedic + Western)"
echo "  ✓ Numerology Engine"
echo "  ✓ Vision AI (Face + Palm Reading)"
echo "  ✓ PDF Report Generation"
echo "  ✓ Transit Alerts"
echo "  ✓ Payment Integration"
echo "  ✓ Video Consultations"
echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║              COMPONENT VERSIONS               ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "  Backend:      FastAPI 0.109.0 (Python 3.11+)"
echo "  Frontend:     Next.js 14.0.4 (React 18)"
echo "  Database:     PostgreSQL 15+ with pgvector"
echo "  Cache:        Redis 7"
echo "  Queue:        RabbitMQ 3.12"
echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║                  QUICK LINKS                  ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "  Backend:      http://localhost:8000"
echo "  Frontend:     http://localhost:3000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Version API:  http://localhost:8000/api/v1/version"
echo ""
echo "  CHANGELOG:    cat CHANGELOG.md"
echo "  Docs:         docs/VERSION_MANAGEMENT.md"
echo ""
